[project]
name = "qa-bot-intelligent-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Renato Silveira", email = "ren.oliv87@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
qa-bot-intelligent-assistant = "qa_bot_intelligent_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
